language: rust
cache: cargo

before_deploy:
  - ./build.sh

matrix:
  include:
    - os: osx
      before_install:
        - brew install gcc
    - os: linux
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update && sudo apt-get install -y gcc-8
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

deploy:
  provider: releases
  api_key: $API_KEY
  file: ${TRAVIS_OS_NAME}.zip
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  email: false
